#!/bin/bash
set -e

TIMEFORMAT=%R

RED="\033[0;31m"
GREEN="\033[0;32m"
NOCOLOR="\033[0m"

if test "$#" -lt 1; then
    echo "Please provide the source code"
    exit 1
fi

if ! test -f "in.txt"; then
    echo "No input file in.txt"
    exit 1
fi

if ! test -f "exp.txt"; then
    echo "No expectation file exp.txt"
    exit 1
fi

echo -en "Compiling\t"
time g++ -std=c++11 -O2 -Wall $1 -o /tmp/cctest_exe

echo -en "Executing\t"
time /tmp/cctest_exe in.txt < in.txt > out.txt

echo "Comparing..."
if cmp -s exp.txt out.txt; then
   echo -e "${GREEN}PASSED!${NOCOLOR}"
else
    echo -e "${RED}FAILED!${NOCOLOR}"
    exit 1
fi
