#!/bin/bash

if test "$#" -lt 1; then
    echo "Please provide a name"
    exit 1
fi

if test -d $1; then
    echo "Solution already existed"
    exit 1
fi

mkdir $1/
cd $1/

cat > src.cc <<EOL
#include <iostream>
#include <algorithm>
#include <cmath>
#include <vector>

using namespace std;

void solve() {
}

int main() {
}
EOL

touch in.txt
touch exp.txt
