#!/bin/bash
set -e

if ! test -f $1; then
    echo "Please provide a cc file"
    exit 1
fi

echo "Compiling..."
g++ -std=c++11 -O2 -Wall $1 -o /tmp/cctest_exe

echo "Executing..."
echo
/tmp/cctest_exe
